<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge">';
echo '<meta name="viewport" content="width= , initial-scale=1.0">';
echo '<title>saarthi</title>';
echo '<link rel="stylesheet" href="./candle.css">';
echo '';
echo '</head>';
echo '<body>';
echo '<p><h1><a href="index.html">SAARTHI</a</h1></p>';
echo '';
echo '';
echo '';
echo '<!-- partial:index.partial.html -->';
echo '<div class="wrapper">';
echo '<div class="candles">';
echo '<div class="light__wave"></div>';
echo '<div class="candle1">';
echo '<div class="candle1__body">';
echo '<div class="candle1__eyes">';
echo '<span class="candle1__eyes-one"></span>';
echo '<span class="candle1__eyes-two"></span>';
echo '</div>';
echo '<div class="candle1__mouth"></div>';
echo '</div>';
echo '<div class="candle1__stick"></div>';
echo '</div>';
echo '';
echo '<div class="candle2">';
echo '<div class="candle2__body">';
echo '<div class="candle2__eyes">';
echo '<div class="candle2__eyes-one"></div>';
echo '<div class="candle2__eyes-two"></div>';
echo '</div>';
echo '</div>';
echo '<div class="candle2__stick"></div>';
echo '</div>';
echo '<div class="candle2__fire"></div>';
echo '<div class="sparkles-one"></div>';
echo '<div class="sparkles-two"></div>';
echo '<div class="candle__smoke-one">';
echo '';
echo '</div>';
echo '<div class="candle__smoke-two">';
echo '';
echo '</div>';
echo '';
echo '</div>';
echo '<div class="floor">';
echo '</div>';
echo '';
echo '';
echo '</div>';
echo '<!-- partial -->';
echo '</body>';
echo '</html>';
?>